# Enable C++
language: cpp

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Compiler selection
matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty
          packages:
            - clang-4.0
      env: COMPILER=clang++-4.0

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
