# Enable C++
language: cpp

# Ubuntu 14.04 Trusty support
dist: trusty

# Compiler selection
matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty main
          packages:
            -clang-4.0

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
