# Enable C++
language: cpp

# Ubuntu 14.04 Trusty support
# Is this really needed?
#sudo: required
dist: trusty

# Compiler selection
matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty
          packages:
            - clang-4.0
            - libsdl2-dev
          env: COMPILER=clang++-4.0

before_install:
  # All dependencies goes here
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Get cmake 3.9.6
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - cmake --version

  # SDL2 pls
  - cd cmake/Modules
  - ls -laF

script:
  # The makening
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make GTest
  - cmake ..
  - make
